"""Fix model inconsistencies in user and history tables

Revision ID: bbceaa18501a
Revises: d519e0d2e7d1
Create Date: 2025-08-05 15:18:30.858103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbceaa18501a'
down_revision: Union[str, None] = 'd519e0d2e7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['income_id'], ['incomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_expense_id'), 'histories', ['expense_id'], unique=False)
    op.create_index(op.f('ix_histories_income_id'), 'histories', ['income_id'], unique=False)
    op.create_index(op.f('ix_histories_user_id'), 'histories', ['user_id'], unique=False)
    
    # Manually added to drop foreign key constraints before dropping the table
    op.drop_constraint('history_ibfk_1', 'history', type_='foreignkey')
    op.drop_constraint('history_ibfk_2', 'history', type_='foreignkey')
    op.drop_constraint('history_ibfk_3', 'history', type_='foreignkey')

    op.drop_index(op.f('ix_history_expense_id'), table_name='history')
    op.drop_index(op.f('ix_history_income_id'), table_name='history')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
    op.execute('SET FOREIGN_KEY_CHECKS=1;')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('SET FOREIGN_KEY_CHECKS=0;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('income_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expense_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name='history_ibfk_1'),
    sa.ForeignKeyConstraint(['income_id'], ['incomes.id'], name='history_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_history_income_id'), 'history', ['income_id'], unique=False)
    op.create_index(op.f('ix_history_expense_id'), 'history', ['expense_id'], unique=False)
    op.drop_index(op.f('ix_histories_user_id'), table_name='histories')
    op.drop_index(op.f('ix_histories_income_id'), table_name='histories')
    op.drop_index(op.f('ix_histories_expense_id'), table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
    op.execute('SET FOREIGN_KEY_CHECKS=1;')